before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: dirmap-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/dirmap.version={{.Version}} -X github.com/k1LoW/dirmap.commit={{.FullCommit}} -X github.com/k1LoW/dirmap.date={{.Date}} -X github.com/k1LoW/dirmap/version.Version={{.Version}}
-
  id: dirmap-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/dirmap.version={{.Version}} -X github.com/k1LoW/dirmap.commit={{.FullCommit}} -X github.com/k1LoW/dirmap.date={{.Date}} -X github.com/k1LoW/dirmap/version.Version={{.Version}}
-
  id: dirmap-windows
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/dirmap.version={{.Version}} -X github.com/k1LoW/dirmap.commit={{.FullCommit}} -X github.com/k1LoW/dirmap.date={{.Date}} -X github.com/k1LoW/dirmap/version.Version={{.Version}}
archives:
-
  id: dirmap-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
-
  id: dirmap-binary
  name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
nfpms:
  - id: dirmap-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - dirmap-linux
    homepage: https://github.com/k1LoW/dirmap
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: dirmap is a tool for generating a directory map.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
